version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: back/Dockerfile
    container_name: towatchlist_app
    env_file:
      - back/.env   # твой .env с DB_HOST, DB_USER, ...
    ports:
      - "3367:8000"
    restart: unless-stopped
