version: "3.9"

services:
  back:
    build:
      context: ./back
      dockerfile: Dockerfile

  front:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      # если нужен baseURL на билде фронта — передаём build-arg
      args:
        VITE_API_BASE_URL: "/api"
