version: "3.9"

services:
  back:
    image: ghcr.io/ssilurs/to_watch_list_back:latest
    container_name: twl-back
    env_file:
      - ./back/.env
    ports:
      - "8000:8000"
    restart: unless-stopped

  front:
    image: ghcr.io/ssilurs/to_watch_list_front:latest
    container_name: twl-front
    depends_on:
      - back
    ports:
      - "8080:80"
    restart: unless-stopped

networks:
  default:
    name: towatchlist-net