name: Build & Push via compose (GHCR)

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Owner lowercase
        run: echo "OWNER_LC=${GITHUB_REPOSITORY_OWNER,,}" >> $GITHUB_ENV

      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3

      - name: Login GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build & Push (compose bake)
        uses: docker/bake-action@v6
        with:
          files: docker-compose.build.yml
          push: true
          targets: |
            back
            front
          set: |
            back.tags=ghcr.io/${{ env.OWNER_LC }}/to_watch_list_back:latest
            front.tags=ghcr.io/${{ env.OWNER_LC }}/to_watch_list_front:latest
            front.args.VITE_API_BASE_URL=/api
