# This workflow builds and publishes a Docker image to GitHub Container Registry (GHCR)
# when changes are pushed to the main branch.
name: Publish Docker image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Log in to GHCR
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          
      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: '${{ github.repository_owner }}'

      - name: Build and push images with docker-compose
        run: |
          docker compose -f docker-compose.yml build
          docker tag towatchlist_back ghcr.io/${{ env.OWNER_LC }}/to_watch_list_back:latest
          docker tag towatchlist_front ghcr.io/${{ env.OWNER_LC }}/to_watch_list_front:latest
          echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin
          docker push ghcr.io/${{ env.OWNER_LC }}/to_watch_list_back:latest
          docker push ghcr.io/${{ env.OWNER_LC }}/to_watch_list_front:latest
